create table if not exists public.regent_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Nova conversa',
  budget_tier text not null default 'minimal'
    check (budget_tier in ('minimal', 'controlled', 'flexible')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists regent_sessions_user_updated_idx
  on public.regent_sessions (user_id, updated_at desc);

alter table public.regent_sessions enable row level security;

grant select, insert, update, delete on public.regent_sessions to authenticated;

drop policy if exists regent_sessions_select_own on public.regent_sessions;
create policy regent_sessions_select_own
  on public.regent_sessions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists regent_sessions_insert_own on public.regent_sessions;
create policy regent_sessions_insert_own
  on public.regent_sessions
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists regent_sessions_update_own on public.regent_sessions;
create policy regent_sessions_update_own
  on public.regent_sessions
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists regent_sessions_delete_own on public.regent_sessions;
create policy regent_sessions_delete_own
  on public.regent_sessions
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.regent_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.regent_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists regent_messages_session_created_idx
  on public.regent_messages (session_id, created_at asc);

create index if not exists regent_messages_user_created_idx
  on public.regent_messages (user_id, created_at desc);

alter table public.regent_messages enable row level security;

grant select, insert, delete on public.regent_messages to authenticated;
grant usage, select on sequence public.regent_messages_id_seq to authenticated;

drop policy if exists regent_messages_select_own on public.regent_messages;
create policy regent_messages_select_own
  on public.regent_messages
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists regent_messages_insert_own on public.regent_messages;
create policy regent_messages_insert_own
  on public.regent_messages
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.regent_sessions s
      where s.id = session_id
        and s.user_id = (select auth.uid())
    )
  );

drop policy if exists regent_messages_delete_own on public.regent_messages;
create policy regent_messages_delete_own
  on public.regent_messages
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
