create table if not exists public.regent_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null references public.regent_sessions(id) on delete cascade,
  title text not null,
  objective text not null,
  status text not null default 'awaiting_approval'
    check (status in ('draft','planning','awaiting_approval','approved','executing','succeeded','failed','rejected','needs_revision','blocked')),
  depth text not null default 'assisted'
    check (depth in ('direct','assisted','elaborated','deep')),
  risk text not null default 'low'
    check (risk in ('low','medium','high')),
  budget_tier text not null default 'minimal'
    check (budget_tier in ('minimal','controlled','flexible')),
  pipeline jsonb not null default '[]'::jsonb,
  picker jsonb,
  human_decision jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists regent_tasks_user_updated_idx
  on public.regent_tasks(user_id, updated_at desc);
create index if not exists regent_tasks_session_idx
  on public.regent_tasks(session_id, created_at desc);

create table if not exists public.regent_task_events (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.regent_tasks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists regent_task_events_task_idx
  on public.regent_task_events(task_id, created_at asc);
create index if not exists regent_task_events_user_idx
  on public.regent_task_events(user_id, created_at desc);

alter table public.regent_tasks enable row level security;
alter table public.regent_task_events enable row level security;

grant select, insert, update, delete on public.regent_tasks to authenticated;
grant select, insert on public.regent_task_events to authenticated;
grant usage, select on sequence public.regent_task_events_id_seq to authenticated;

drop policy if exists regent_tasks_select_own on public.regent_tasks;
create policy regent_tasks_select_own on public.regent_tasks
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists regent_tasks_insert_own on public.regent_tasks;
create policy regent_tasks_insert_own on public.regent_tasks
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.regent_sessions s
      where s.id = session_id and s.user_id = (select auth.uid())
    )
  );

drop policy if exists regent_tasks_update_own on public.regent_tasks;
create policy regent_tasks_update_own on public.regent_tasks
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists regent_tasks_delete_own on public.regent_tasks;
create policy regent_tasks_delete_own on public.regent_tasks
  for delete to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists regent_task_events_select_own on public.regent_task_events;
create policy regent_task_events_select_own on public.regent_task_events
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists regent_task_events_insert_own on public.regent_task_events;
create policy regent_task_events_insert_own on public.regent_task_events
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.regent_tasks t
      where t.id = task_id and t.user_id = (select auth.uid())
    )
  );